# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
                ('task_type', models.CharField(choices=[('user', 'User Task'), ('service', 'Service Task'), ('receive', 'Receive Task'), ('send', 'Send Task'), ('business_rule', 'Business Rule Task'), ('script', 'Script Task')], max_length=20, verbose_name='Type')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Process', verbose_name='Task')),
            ],
        ),
    ]
