# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('user', 'User Task'), ('service', 'Service Task'), ('receive', 'Receive Task'), ('send', 'Send Task'), ('business_rule', 'Business Rule Task'), ('script', 'Script Task'), ('task', 'Task')], max_length=20, verbose_name='Type'),
        ),
    ]
