# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20171205_1842'),
        ('profiles', '0003_auto_20171205_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='suite',
            field=models.ManyToManyField(blank=True, to='resources.Product', verbose_name='Application Suite'),
        ),
    ]
