# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180313_0357'),
        ('profiles', '0004_organization_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ResourceType', verbose_name='Application Type'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
