# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180313_0357'),
        ('profiles', '0005_auto_20180313_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recommended_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_tasks', to='resources.ResourceType', verbose_name='Recommended App'),
        ),
        migrations.AlterField(
            model_name='task',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ResourceType', verbose_name='Application Type'),
        ),
    ]
