# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_organization_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('user', 'User Task'), ('service', 'Service Task'), ('receive', 'Receive Task'), ('send', 'Send Task'), ('business_rule', 'Business Rule Task'), ('script', 'Script Task'), ('task', 'Task'), ('manual', 'Manual Task')], max_length=20, verbose_name='Type'),
        ),
    ]
