# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-27 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_resource_type'),
        ('profiles', '0008_auto_20181027_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource', verbose_name='Resource'),
        ),
    ]
