# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_resource_type'),
        ('profiles', '0009_task_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recommended_app',
        ),
        migrations.AddField(
            model_name='task',
            name='classified_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_tasks', to='resources.ResourceType', verbose_name='Classified Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='recommended_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_used_for_recommending', to='resources.ResourceType', verbose_name='Recommended Resource'),
        ),
    ]
