# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181029_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recommended_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_used_for_recommending', to='resources.Resource', verbose_name='Recommended Resource'),
        ),
    ]
