# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181029_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='resources.Resource', verbose_name='Resource'),
        ),
    ]
