# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20181030_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profiles.Process', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource', verbose_name='Resource'),
        ),
    ]
