# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_auto_20180314_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='uploads/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organization', verbose_name='Organization')),
            ],
        ),
    ]
