# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-27 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180313_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Resource',
        ),
    ]
