# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20181027_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='available_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='multiplatform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='open_source',
            field=models.BooleanField(default=False),
        ),
    ]
